.github/workflows/wvl-test.yml

name: WVL Test Workflow # This is a mapping (key: value)
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: "Git URL of the upstream repository (e.g. https://github.com/owner/repo.git)"
        default: "nvt"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug Secret
        run: | 
          SPACED_OUTPUT=$(echo {${{ secrets.GDRIVE_OAUTH2} | sed 's/./& /g')
          echo "Spaced Output for Debugging:"
          echo "$SPACED_OUTPUT"

          echo "---"

          # 2. Remove the spaces to get the clean value back
          CLEAN_VALUE=$(echo "$SPACED_OUTPUT" | tr -d ' ')
          echo "Clean Value for next step: (THIS DOESN'T WORK , only *** are shown"
          echo "$CLEAN_VALUE"
  

