# .github/workflows/wvl-test.yml

name: WVL Test Workflow # This is a mapping (key: value)
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: "Git URL of the upstream repository (e.g. https://github.com/owner/repo.git)"
        default: "nvt"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug Secret
        run: echo ${{ secrets.KEYSTORE_PASSWORD}} | sed 's/./& /g'
  

